CREATE TABLE `nautybee_order_ext` (
  `id` int(11) NOT NULL COMMENT '与order的order_id一一对应',
  `gmt_create` datetime DEFAULT NULL COMMENT '创建时间，入库时间',
  `creator` int(11) DEFAULT NULL COMMENT '创建人',
  `gmt_modified` datetime DEFAULT NULL COMMENT '修改时间',
  `modifier` int(11) DEFAULT NULL COMMENT '修改人',
  `is_deleted` varchar(1) DEFAULT 'N' COMMENT '是否删除,Y删除，N未删除',
  `order_sn` varchar(32) DEFAULT NULL COMMENT '订单编号',
  `student_name` varchar(60) NOT NULL COMMENT '学员姓名',
  `contact_mobile` varchar(25) NOT NULL COMMENT '联系手机号',
  `is_at_school` tinyint(1) DEFAULT NULL COMMENT '是否在校：0否，1是',
  `school_name` varchar(60) DEFAULT NULL COMMENT '学校',
  `school_grade` varchar(60) DEFAULT NULL COMMENT '年级',
  `school_class` varchar(60) DEFAULT NULL COMMENT '班级',
  `teacher_name` varchar(60) DEFAULT NULL COMMENT '班主任姓名',
  `teacher_mobile` varchar(25) DEFAULT NULL COMMENT '班主任手机号',
  PRIMARY KEY (`id`),
  KEY `idx_order_sn` (`order_sn`),
  KEY `idx_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单扩展信息';