CREATE TABLE `nautybee_common_resources` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `creator` int(11) NOT NULL DEFAULT '-1000' COMMENT '创建人',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `modifier` int(11) NOT NULL DEFAULT '-1000' COMMENT '最后修改人',
  `gmt_modified` datetime NOT NULL COMMENT '最后修改时间',
  `is_deleted` char(1) NOT NULL DEFAULT 'N' COMMENT '是否删除',
  `app_name` varchar(16) NOT NULL COMMENT '所属应用',
  `type` varchar(64) NOT NULL COMMENT '资源名，一般是大写的英文',
  `key` varchar(512) NOT NULL COMMENT '资源的Key',
  `value` varchar(512) NOT NULL COMMENT '资源的Value',
  `value_1` varchar(2000) DEFAULT NULL COMMENT '通用值字段',
  `value_2` varchar(2000) DEFAULT NULL COMMENT '通用值字段',
  `value_3` varchar(3000) DEFAULT NULL COMMENT '通用值字段',
  `value_4` varchar(3000) DEFAULT NULL COMMENT '通用值字段',
  `value_5` varchar(4000) DEFAULT NULL COMMENT '通用值字段',
  `value_6` varchar(1000) DEFAULT NULL COMMENT '通用值字段',
  `value_7` text COMMENT '通用值字段',
  `order_idx` varchar(16) DEFAULT NULL COMMENT '显示次序',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='通用资源表';